version: "3.9"
services:
  users-service:
    build: .
    container_name: aithronix-identity
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aithronix-identity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: aithronix-user-db
    environment:
      POSTGRES_DB: aithronix-identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - userdata:/var/lib/postgresql/data

volumes:
  userdata:
